version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: agenda
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: agenda_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/agenda
      SPRING_DATASOURCE_USERNAME: agenda_user
      SPRING_DATASOURCE_PASSWORD: agenda_pass
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data: